name: artifact

on: [push]

env:
  FILE_NAME: artifact1

jobs:
  build:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Upload artifacts 
      uses: actions/upload-artifact@v4.0.0
      with:
        name: ${{ env.FILE_NAME }}
        path: .

